import type { Metadata } from "next";
import { Toaster } from "sonner";
import { ConditionalHeader } from "@/components/conditional-header";
import { ConditionalFooter } from "@/components/conditional-footer";
import { ClientSidebarProvider } from "@/components/client/sidebar-context";
import { AdminSidebarProvider } from "@/components/admin/sidebar-context";
import "./globals.css";
import "./tw-animate.css";

// NOTE: Using `next/font/google` attempts to fetch fonts at build time.
// On environments without network access this causes build failures.
// For now we use local/system fallbacks defined in `globals.css`.

export const metadata: Metadata = {
  title: "SSIT Portal",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <ClientSidebarProvider>
          <AdminSidebarProvider>
            <ConditionalHeader />
            {children}
            <ConditionalFooter />
          </AdminSidebarProvider>
        </ClientSidebarProvider>
        <Toaster richColors position="bottom-right" />
      </body>
    </html>
  );
}
