import type { Metadata } from "next";
import { Poppins, JetBrains_Mono } from "next/font/google";
import { Toaster } from "sonner";
import { ConditionalHeader } from "@/components/conditional-header";
import { ConditionalFooter } from "@/components/conditional-footer";
import { ClientSidebarProvider } from "@/components/client/sidebar-context";
import { AdminSidebarProvider } from "@/components/admin/sidebar-context";
import "./globals.css";
import "./tw-animate.css";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "SSIT Portal",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${jetbrainsMono.variable} antialiased`}
      >
        <ClientSidebarProvider>
          <AdminSidebarProvider>
            <ConditionalHeader />
            {children}
            <ConditionalFooter />
          </AdminSidebarProvider>
        </ClientSidebarProvider>
        <Toaster richColors position="bottom-right" />
      </body>
    </html>
  );
}
