import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";
import { ConditionalHeader } from "@/components/conditional-header";
import { ClientSidebarProvider } from "@/components/client/sidebar-context";
import { AdminSidebarProvider } from "@/components/admin/sidebar-context";
import "./globals.css";
import "./tw-animate.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClientSidebarProvider>
          <AdminSidebarProvider>
            <ConditionalHeader />
            {children}
          </AdminSidebarProvider>
        </ClientSidebarProvider>
        <Toaster richColors position="bottom-right" />
      </body>
    </html>
  );
}
